Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 256
      Handler: com.revature.get_nodes.GetAllSubForumsHandler
      CodeUri: C:\Users\lunah\Documents\revature_projects\project-3\getSubforum
      Runtime: java8.al2