package com.revature.models;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;


import java.time.LocalDateTime;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "ForumNodes")
public class Node {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String subject;

    @DynamoDBAttribute
    private List<String> ancestors;

    @DynamoDBIndexHashKey(attributeName = "parent", globalSecondaryIndexName = "parent-date_created-index")
    private String parent;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private int child_count;


    @DynamoDBIndexRangeKey(attributeName = "date_created", globalSecondaryIndexName = "parent-date_created-index")
    private String date_created;

    @DynamoDBAttribute
    private String owner;

    @DynamoDBAttribute
    private List<String> tags;

}
